# -*- coding: utf-8 -*-
"""guided-bertopic-modeling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p92aOGOTkR025z42i2TwSupp6GZ_L42M

Guided BERTopic has two main steps:

First, we create embeddings for each seeded topics by joining them and passing them through the document embedder. These embeddings will be compared with the existing document embeddings through cosine similarity and assigned a label. If the document is most similar to a seeded topic, then it will get that topic's label. If it is most similar to the average document embedding, it will get the -1 label. These labels are then passed through UMAP to create a semi-supervised approach that should nudge the topic creation to the seeded topics.

Second, we take all words in seed_topic_list and assign them a multiplier larger than 1. Those multipliers will be used to increase the IDF values of the words across all topics thereby increasing the likelihood that a seeded topic word will appear in a topic. This does, however, also increase the chance of an irrelevant topic having unrelated words. In practice, this should not be an issue since the IDF value is likely to remain low regardless of the multiplier. The multiplier is now a fixed value but may change to something more elegant, like taking the distribution of IDF values and its position into account when defining the multiplier.
"""

# !pip install sentence_transformers
# !pip install hdbscan
# !pip install UMAP
# !pip install nltk
# !pip install bertopic
# !pip install languages
# #!pip install clean-text
# !pip install spacy_langdetect
# !pip install pyLDAvis
# !pip install matplotlib
# !pip install json
# !pip install stop_word_list
# !pip install clean_text
# !pip install stopwords

from bertopic import BERTopic
#from sklearn.datasets import fetch_20newsgroups
# data = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))
# docs = data["data"]
# categories = data["target"]
# category_names = data["target_names"]

import pandas as pd
# df = pd.read_json('/content/clipsubset.json')
# captions = df['caption'].values

# df.head()

# captions

# from langdetect import detect
# captions_eng = []
# all = []

# for caption in captions:
#     try:
#         language = detect(caption)
#         if detect(caption) == 'en':
#             captions_eng.append(caption)
#     except:
#         language = "error"
#         print("This row throws and error:", caption)
#     #all.append(language)   
#     #all.append(row)
# captions_eng



opsis_labels = ["Minestrone with beef",
"Beef chili",
"Oatmeal with flax seeds and apple",
"Blueberry shortcake",
"Roast beef sandwich",
"Turkey Sandwich",
"Classic Caesar salad",
"Mixed berry shortcake",
"Veggie sandwich",
"Classic Caesar salad with edamame",
"Oatmeal with diced apple",
"Classic minestrone with leafy greens",
"Chocolate chip cookies with pecans",
"Lasagna with meat sauce",
"Strawberry shortcake",
"Vegetarian pizza",
"Chocolate chip cookies",
"Oatmeal with diced apple and pistachios",
"Classic Caesar salad with chicken",
"Vegetarian lasagna with spinach",
"Classic minestrone",
"Chicken and bean chili",
"Vegetarian lasagna",
"Beef Steak",
"Tilapia",
"Banana",
"Green beans",
"pecans",
"Baked Beans",
"Cherries",
"Macaroni and cheese",
"brown rice",
"Brownie ",
"White Bread",
"Carrots",
"green peas",
"cornbread",
"Potato",
"Canned pear halves",
"Corn",
"String cheese",
"Fried Chicken Breast",
"Fried eggs",
"Peanut Butter",
"Pork roast",
"chicken patty",
"Pear ",
"tapioca pudding, vanilla and other flavors, homemade",
"rice pudding, plain, made with egg",
"plain yogurt, lowfat",
"oatmeal, regular cooking",
"macaroni noodles",
"angel hair pasta",
"chocolate pudding, from mix, instant",
"garbanzo beans",
"cottage cheese, regular (4% fat)",
"Blueberries",
"couscous",
"rice noodles",
"Strawberries",
"chocolate ice cream",
"vanilla ice cream",
"chili, canned, with beans and beef, less sodium",
"pumpkin cookies",
"dark chocolate covered almonds",
"caramel popcorn",
"cheesecake",
"eclair",
"macaroon",
"ice cream sandwich",
"chocolate cheesecake",
"chocolate coated cookies",
"Rice Krispies treats",
"animal crackers",
"oatmeal cookies",
"chocolate-coated graham crackers",
"peanut butter sandwich cookies",
"molasses cookies",
"sugar wafer cookies",
"mochi",
"key lime pie",
"lava cake",
"wafer cookies",
"gingerbread cookies",
"chocolate covered peanuts",
"windmill cookies",
"angel food cake",
"yogurt coated pretzels",
"butter cookie with filling",
"apple turnover",
"white chocolate macadamia nut cookies",
"Apple pie",
"thumbprint cookie",
"butter waffle cookies",
"ice cream cone, cake or wafer type",
"maraschino cherries",
"chocolate cream pie",
"pizelle cookies",
"shortbread cookies",
"biscotti",
"pecan pie",
"madeleine cookies",
"rice cake, flavored",
"chocolate covered pretzels",
"ice cream bar",
"peanut butter cookies",
"mint cookies with chocolate coating",
"chocolate covered peanut clusters",
"chocolate-covered toffee",
"lemon bars",
"ice cream cone, sugar type",
"yogurt coated shortbread ",
"half moon cookies",
"chocolate mousse",
"Cookie Sandwich",
"oatmeal raisin cookies",
"MNM cookies",
"cream puff",
"Danish pastry with cheese filling",
"Maria cookies",
"vanilla sandwich cookies",
"Lacys cookies",
"meringue, angel cookies",
"brownie-cookie bar",
"snickerdoodle cookies",
"coconut cream pie",
"Danish pastry with fruit filling",
"dark chocolate covered raisins",
"lady fingers",
"chocolate covered strawberries",
"iced sugar cookies",
"fortune cookies",
"Cashews",
"Tuna salad",
"Mashed Potatoes",
"Almonds",
"Sweet potatoes",
"Pancake",
"Cabbage",
"Canadian bacon",
"Chicken drumstick",
"Shrimp",
"Donut",
"Summer squash",
"Potato chips",
"Hot dog",
"Chicken breast",
"Scrambled eggs",
"Chicken thigh",
"Pickles",
"French Fries",
"Cured Ham",
"Beef steak",
"Peach",
"Pork chops",
"Waffles",
"Walnuts",
"Cucumber",
"Dried mango",
"Celery",
"Onion rings ",
"Pinto Beans",
"Asparagus",
"Pistachios",
"Brussels sprouts",
"Pasta salad",
"Peanuts",
"Bell pepper",
"Potato salad",
"Chicken wing ",
"Bagel",
"Broccoli",
"English Muffin",
"Pumpkin pie",
"Cauliflower",
"Apple",
"Raspberries",
"Black beans",
"Chicken salad",
"Cantaloupe",
"Watermelon ",
"Fruit salad",
"Meatloaf",
"Chocolate sandwich cookies",
"Mango",
"Hashed brown potatoes",
"Popcorn",
"Poached eggs",
"Chicken tenders ",
"Pretzel twists or rings",
"Chicken nuggets",
"Cheese cracker",
"Applesauce",
"Refried bean ",
"Egg salad ",
"Mozzarella sticks",
"Tortilla chips",
"Coffee cake ",
"Dried apple",
"Tomato",
"White rice",
"Devil's food cake",
"Brownie",
"Potato chips, ruffled or rippled",
"Orange ",
"chocolate brownie, frosted",
"Yogurt",
"chocolate brownie with nuts",
"Biscuit",
"Raisins ",
"Grapes",
"Bacon",
"Wheat cracker",
"Snack pie",
"Spanish rice",
"Zucchini",
"Clementine",
"Croissant ",
"mushrooms",
"ground beef",
"fig bars",
"melon, honeydew",
"grapefruit",
"avocado",
"pork rinds",
"lima beans",
"almond butter",
"boiled potato",
"ice cream cone",
"macadamia nuts",
"ham lunchmeat",
"paella",
"fish sticks",
"tater tots",
"radish",
"kale",
"apricot",
"mixed nuts",
"ground turkey",
"marshmallow",
"egg white",
"saurkraut",
"scalloped potatoes",
"lamb chops",
"salmon",
"chicken lunchmeat",
"lentils",
"roll",
"ground pork",
"okra",
"strudel",
"bacon bits",
"truffles",
"corn dog",
"rice and beans",
"dried apricot",
"dried prune",
"parsnip",
"jalapeno peppers",
"pork sausage",
"hard boiled eggs",
"salmon patty",
"egg subsitute",
"plum",
"salami",
"jicama",
"beef lunchmeat",
"pepperoni",
"croutons",
"pumpkin seeds",
"turkey light meat",
"beef jerky",
"tortellini",
"kidney beans",
"pineapple",
"tofu, raw",
"guacamole",
"deviled eggs",
"sushi",
"prosciutto",
"eggplant",
"rice pilaf",
"quinoa",
"dried figs",
"onion",
"soft pretzel",
"meatballs",
"snow peas",
"hummus",
"edamame",
"muffin, banana",
"tamale",
"graham crackers",
"spinach dip",
"french toast sticks",
"tuna, canned",
"turkey lunchmeat",
"dates",
"beef brisket",
"artichoke",
"egg yolk",
"falafel",
"bratwurst",
"kimchi",
"muffin, chocolate chip",
"Brazil nuts",
"beef stew",
"tapenade",
"water chestnuts",
"pork ribs",
"Chard",
"colby monteray jack",
"Pita bread",
"blackberries",
"sunflower seed",
"scone",
"bulgur",
"Apple Crisp ",
"canned potato",
"coleslaw",
"scallions",
"papaya",
"dried cranberries",
"fruit cocktail",
"Chicken fried steak",
"ravioli",
"Bamboo Shoots",
"hearts of palm",
"Kiwi",
"queso fresco",
"liverworst spread",
"stuffing",
"salisbury steak",
"wild rice",
"pretzel nuggets",
"bread sticks",
"Mandrian segments",
"sprouts",
"cod ",
"black olives",
"corn nuts",
"beets",
"egg rolls",
"Chorizo, beef",
"roasted potatoes",
"turnip",
"sun-dried tomato",
"summer sausage",
"gnocchi",
"Banana chips",
"taco shell",
"fennel bulb",
"Green olives",
"beef liver",
"Diced ham",
"barley",
"cupcake",
"rice cake",
"Italian sausage",
"whole wheat rotini noodles",
"whole wheat orzo noodles",
"meat ravioli, without sauce",
"egg noodles",
"rotini",
"whole wheat spaghetti noodles",
"rigatoni",
"spaghetti noodles",
"orzo noodles",
"penne",
"cheese ravioli, without sauce",
"lasagna noodles",
"spinach ravioli, without sauce",
"chicken tortellini, without sauce",
"cheese tortellini, without sauce",
"gluten free pasta, lentil",
"linguini",
"farfalle",
"fettucini noodles, without egg",
"ziti"]

# labels_to_add = opsis_labels
# indices = [category_names.index(label) for label in labels_to_add]
# y = [label if label in indices else -1 for label in categories]

# topic_model = BERTopic(verbose=True).fit(docs, y=y)

"""Guided Topic Modeling"""

from bertopic import BERTopic
docs = opsis_labels
topic_model = BERTopic(seed_topic_list=opsis_labels)
topics, probs = topic_model.fit_transform(docs)

topic_model

topic_model.topics

topic_model.visualize_term_rank()

topic_model.visualize_hierarchy()

topic_model.visualize_heatmap()

topic_model.visualize_topics()

topic_model.visualize_barchart()

topic_model.visualize_documents(docs)

topic_model.get_topic_freq()
